name: CI Karate

on:
  push:
    branches:
      - main
  pull_rquest:

jobs:
  # Lint y validaciones b√°sicas
  lint_and_check:
    name: Lint & Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run code quality checks
        run: ./gradlew check

  karte_build_and_run_test6:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.1

      - name: Steup java
        uses: actions/steup-java@v4
        with:
          distribuction: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
