# Nombre de workflow
name: CI Karate

# Evento que activa workflow
on:
  push:
    branches:
      - main

# Trabajos del workflow
jobs:
  # Nombre del trabajo
  karate_build_and_run_test:
    # Maquina virtual donde se ejecuta el workflow
    runs-on: ubuntu-latest
    # Pasos para ejecutar en la máquina virtual
    steps:
      # Descargar nuestro repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuración de Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      # Configuración de Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      # Ejecutar pruebas
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      # Subir el reporte de pruebas como un artefacto
      - name: Upload test report
        # Se ejecuta siempre para poder ver el reporte incluso si las pruebas fallan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: build/cucumber-reports/
